#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:15:00
#PBS -N dwiAlignDtiinit
#PBS -V

module load singularity 2> /dev/null

# alignment
time singularity exec -e docker://brainlife/fsl:5.0.9 ./alignment.sh

# rotate bvecs
time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./rotation/rotateBvecs

if [ ! -s dwi.nii.gz ];
then
	echo "Dwi alignment to dtiinit complete"
	exit 0
else
	echo "Aligned dwi missing"
	exit 1
fi
